repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]




