name: 🚀 Feature
description: Suggest a new feature or improvement
title: "[FEATURE]: "
labels: [type/feature]
body:
  - type: textarea
    id: what
    attributes:
      label: What do you want to add?
      description: Describe the feature or task clearly.
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is it needed?
      description: Explain why this matters (technical or strategic).
    validations:
      required: false

  - type: textarea
    id: criteria
    attributes:
      label: Acceptance criteria
      description: What needs to be true for this to be considered 
complete?
      placeholder: |
        - Handles edge cases
        - Passes all tests
        - Clean code
    validations:
      required: false

  - type: input
    id: phase
    attributes:
      label: Roadmap Phase
      placeholder: Phase 2 – Proxy Layer
    validations:
      required: false

