name: 🚀 Feature
description: Suggest a new feature or improvement
title: "[FEATURE]: "
labels: [type/feature]
body:
  - type: textarea
    id: what
    attributes:
      label: What do you want to add?
      description: Describe the feature or task clearly.
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is it needed?
    validations:
      required: false

